import { readFileSync } from "node:fs";
import path from "node:path";

import { expect, test, vi } from "vitest";

vi.mock("next/font/google", () => ({
  Geist: () => ({ variable: "--font-geist-sans" }),
  Geist_Mono: () => ({ variable: "--font-geist-mono" }),
}));

import { metadata } from "./layout";

test("layout metadata is branded for the showcase site", () => {
  expect(metadata.title).toBe("Lens Archive");
  expect(metadata.description).toBe("面向摄影师与模特的沉浸式作品展示与约拍平台。");
  expect(metadata.title).not.toBe("Create Next App");
  expect(metadata.description).not.toBe("Generated by create next app");
});

test("global styles define the branded visual tokens", () => {
  const css = readFileSync(path.join(process.cwd(), "src/app/globals.css"), "utf8");

  expect(css).toContain("--background: #050816;");
  expect(css).toContain("--foreground: #f8fafc;");
  expect(css).toContain("--font-sans: var(--font-geist-sans);");
  expect(css).not.toContain("--background: #ffffff;");
  expect(css).not.toContain("--foreground: #171717;");
});
