import { readFileSync } from "node:fs";
import path from "node:path";

import { expect, test, vi } from "vitest";

vi.mock("next/font/google", () => ({
  Geist: () => ({ variable: "--font-geist-sans" }),
  Geist_Mono: () => ({ variable: "--font-geist-mono" }),
  Cormorant_Garamond: () => ({ variable: "--font-cormorant" }),
}));

import { metadata } from "./layout";

test("layout metadata is branded for the high-match discovery site", () => {
  expect(metadata.title).toBe("Lens Archive");
  expect(metadata.description).toBe("让作品被更相关的观众持续发现，并进入可信主页与联系路径。");
  expect(metadata.title).not.toBe("Create Next App");
  expect(metadata.description).not.toBe("Generated by create next app");
});

test("global styles define the branded visual tokens", () => {
  const css = readFileSync(path.join(process.cwd(), "src/app/globals.css"), "utf8");

  expect(css).toContain("--background: #f5efe6;");
  expect(css).toContain("--foreground: #16110c;");
  expect(css).toContain("--surface-strong: rgba(255, 252, 248, 0.94);");
  expect(css).toContain("--font-sans: var(--font-geist-sans);");
  expect(css).toContain("--font-display: var(--font-cormorant);");
  expect(css).not.toContain("--background: #ffffff;");
  expect(css).not.toContain("--foreground: #171717;");
});
